apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "Schools-API-Service"
  annotations:
   github.com/project-slug: TluwaniMS/node-js-server-unit-and-integration-testing
spec:
  type: openapi
  owner: "Backstage"
  lifecycle: development
  definition:
    $text: https://avaf-reference-data.avaf-uat.bolt.270-nonprod.caas.absa.co.za/swagger-ui/index.html#/
